/* ── App-wide Constants ── */

export const APP_NAME = 'PrivacyShield Agent';
export const APP_TAGLINE = 'Task-Aware Privacy Firewall for Visual Browser Agents';
export const APP_VERSION = '1.0.0-mvp';

/* ── Privacy Decision Types ── */
export const PRIVACY_DECISION = {
  ALLOW: 'ALLOW',
  TRANSFORM: 'TRANSFORM',
  BLOCK: 'BLOCK',
};

/* ── PII Types ── */
export const PII_TYPES = {
  // Government IDs
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
  VOTER_ID: 'VOTER_ID',
  DRIVING_LICENSE: 'DRIVING_LICENSE',

  // Personal
  PERSON_NAME: 'PERSON_NAME',
  EMAIL: 'EMAIL',
  PHONE_NUMBER: 'PHONE_NUMBER',
  DATE_OF_BIRTH: 'DATE_OF_BIRTH',
  ADDRESS: 'ADDRESS',
  FACE: 'FACE',

  // Financial
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  IFSC_CODE: 'IFSC_CODE',
  CREDIT_CARD: 'CREDIT_CARD',
  UPI_ID: 'UPI_ID',
  FINANCIAL_AMOUNT: 'FINANCIAL_AMOUNT',

  // Security
  PASSWORD: 'PASSWORD',
  OTP: 'OTP',
  CVV: 'CVV',
  PIN: 'PIN',
  SECRET_ANSWER: 'SECRET_ANSWER',

  // Vehicle
  VEHICLE_REG: 'VEHICLE_REG',

  // Other
  IP_ADDRESS: 'IP_ADDRESS',
  BIOMETRIC: 'BIOMETRIC',
};

/* ── Default Sensitivity Mapping ── */
export const DEFAULT_SENSITIVITY = {
  // BLOCK - never transmitted
  [PII_TYPES.AADHAAR]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.PAN]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.PASSPORT]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.VOTER_ID]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.DRIVING_LICENSE]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.BANK_ACCOUNT]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.CREDIT_CARD]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.PASSWORD]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.OTP]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.CVV]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.PIN]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.BIOMETRIC]: PRIVACY_DECISION.BLOCK,

  // TRANSFORM - replaced with semantic placeholder
  [PII_TYPES.PERSON_NAME]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.EMAIL]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.PHONE_NUMBER]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.DATE_OF_BIRTH]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.ADDRESS]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.FACE]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.IFSC_CODE]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.UPI_ID]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.FINANCIAL_AMOUNT]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.VEHICLE_REG]: PRIVACY_DECISION.TRANSFORM,
  [PII_TYPES.SECRET_ANSWER]: PRIVACY_DECISION.BLOCK,
  [PII_TYPES.IP_ADDRESS]: PRIVACY_DECISION.TRANSFORM,
};

/* ── Sensitivity Weights (for Privacy Exposure Score) ── */
export const SENSITIVITY_WEIGHTS = {
  [PRIVACY_DECISION.BLOCK]: 10,
  [PRIVACY_DECISION.TRANSFORM]: 5,
  [PRIVACY_DECISION.ALLOW]: 0,
};

/* ── Placeholder Templates ── */
export const PLACEHOLDERS = {
  [PII_TYPES.AADHAAR]: '[BLOCKED_GOVT_ID]',
  [PII_TYPES.PAN]: '[BLOCKED_GOVT_ID]',
  [PII_TYPES.PASSPORT]: '[BLOCKED_GOVT_ID]',
  [PII_TYPES.VOTER_ID]: '[BLOCKED_GOVT_ID]',
  [PII_TYPES.DRIVING_LICENSE]: '[BLOCKED_GOVT_ID]',
  [PII_TYPES.PERSON_NAME]: '[PERSON_NAME]',
  [PII_TYPES.EMAIL]: '[EMAIL_ADDRESS]',
  [PII_TYPES.PHONE_NUMBER]: '[PHONE_NUMBER]',
  [PII_TYPES.DATE_OF_BIRTH]: '[DATE_OF_BIRTH]',
  [PII_TYPES.ADDRESS]: '[ADDRESS]',
  [PII_TYPES.FACE]: '[FACE_REDACTED]',
  [PII_TYPES.BANK_ACCOUNT]: '[BLOCKED_ACCOUNT]',
  [PII_TYPES.IFSC_CODE]: '[BANK_CODE]',
  [PII_TYPES.CREDIT_CARD]: '[BLOCKED_CARD]',
  [PII_TYPES.UPI_ID]: '[UPI_ID]',
  [PII_TYPES.FINANCIAL_AMOUNT]: '[BLOCKED_FINANCIAL]',
  [PII_TYPES.PASSWORD]: '[BLOCKED_PASSWORD]',
  [PII_TYPES.OTP]: '[BLOCKED_OTP]',
  [PII_TYPES.CVV]: '[BLOCKED_CVV]',
  [PII_TYPES.PIN]: '[BLOCKED_PIN]',
  [PII_TYPES.SECRET_ANSWER]: '[BLOCKED_SECRET]',
  [PII_TYPES.VEHICLE_REG]: '[VEHICLE_REG]',
  [PII_TYPES.IP_ADDRESS]: '[IP_ADDRESS]',
  [PII_TYPES.BIOMETRIC]: '[BLOCKED_BIOMETRIC]',
};

/* ── Action Types ── */
export const ACTION_TYPES = {
  CLICK: 'click',
  TYPE: 'type',
  SCROLL: 'scroll',
  SELECT: 'select',
  NAVIGATE: 'navigate',
  WAIT: 'wait',
  EXTRACT: 'extract',
};

/* ── Risk Levels ── */
export const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  BLOCKED: 'BLOCKED',
};

/* ── Context Modes ── */
export const CONTEXT_MODES = {
  DOM_ONLY: 'dom_only',
  DOM_SCREENSHOT: 'dom_screenshot',
  SCREENSHOT_DOM: 'screenshot_dom',
};

/* ── Demo Scenarios ── */
export const SCENARIOS = {
  GOVERNMENT: 'government',
  BANKING: 'banking',
  NORMAL: 'normal',
  ATTACK: 'attack',
};

export const SCENARIO_LABELS = {
  [SCENARIOS.GOVERNMENT]: 'Government Portal',
  [SCENARIOS.BANKING]: 'Banking Portal',
  [SCENARIOS.NORMAL]: 'E-Commerce',
  [SCENARIOS.ATTACK]: 'Attack Demo',
};

/* ── Browser Adapter Modes ── */
export const BROWSER_MODES = {
  WEB: 'web',
  CHROME: 'chrome',
  FIREFOX: 'firefox',
};

/* ── VLM Providers ── */
export const VLM_PROVIDERS = {
  GEMINI: 'gemini',
  OPENAI: 'openai',
  OLLAMA: 'ollama',
};
